#!/usr/bin/env bash
# Mutable project bootstrap content for setup.sh.
#
# The two phases preserve the historical docs-install interleave. Bootstrap
# paths are intentionally absent from infrastructure replacement registries.
# setup_project_bootstrap_before_docs exports ARP_UUID, ARP_DATE, and
# ARP_VERSION for the deployment manifest.

setup_project_bootstrap_before_docs() {
local ARP_HASH ARP_SEMVER ARP_MODE ARP_PROVENANCE MAIN_TEX_TEMPLATE IA_TEX_TEMPLATE
local -a STAGE2B_DIRS
# ── Create project directories and initial files ──
echo "Creating project structure..."

if [ "$MODE" = "report" ]; then
    # Report mode: read-only `submission/` (user drops the paper here), parallel
    # `audits/` outputs, single `report/referee_report.md` deliverable, and a
    # process log. No `paper/`, `code/`, `data/`, or `references/` — there is no
    # paper to write, no code to run on behalf of the authors, no data to fetch.
    # (The empirical extension still installs `code/utils/` for shared skills,
    # but no `code/analysis/` etc.)
    mkdir -p "$P/submission" "$P/audits" "$P/report" "$P/process_log"
    cat > "$P/submission/README.md" <<'SUBREADME'
# submission/ — drop the paper to be refereed here

Supported formats:

- PDF only — `submission/paper.pdf`
- LaTeX source bundle — `submission/main.tex` + `submission/sections/*.tex` + `submission/refs.bib` (optionally `submission/tables/`, `submission/figures/`, an internet appendix)
- Both — PDF for the audit agents that prefer typeset output, source for the
  agents that re-derive equations or verify cite keys

The pipeline treats this directory as **read-only**. Audit agents read from
here; they write to `audits/<name>.md`. The synthesizer writes the final
report to `report/referee_report.md`. The original submission is never
modified.

After dropping the submission, launch the runtime (claude / codex / gemini)
and say "run" or "start". The orchestrator runs Step 1 triage, fans out the
audit agents in parallel, then launches `report-synthesizer` to produce the
editor-facing referee report.

Each deployment is one-shot. If the editor sends a revised submission later,
that is a fresh `setup.sh --mode report ...` deployment on a fresh
`submission/` folder; this folder is not designed for v1/v2 cycling.
SUBREADME
else
    mkdir -p "$P/code/analysis" "$P/code/download" "$P/code/tmp" "$P/code/explore"
    mkdir -p "$P/data"
    mkdir -p "$P/paper/sections" "$P/paper/simulated_referee_reports"
    mkdir -p "$P/references"
fi

# ---------------------------------------------------------------------
# Pipeline fingerprint: arpipeline.sty + main.tex skeleton
# Bakes a deployment-unique UUID into four layers (LaTeX source commands,
# hyperref PDF metadata, custom /Info dict entries, and per-page white-
# on-white grep marker) so every paper produced by this deployment
# carries the magic prefix ARPIPELINE-FP-V1 for distribution detection.
# ---------------------------------------------------------------------
ARP_UUID=$(python3 -c 'import uuid; print(uuid.uuid4())' 2>/dev/null)
ARP_DATE=$(date -u +%Y-%m-%d)
# Version stamp = human-readable semver (from the VERSION file, the single
# source of truth) + exact build provenance (git short hash), e.g.
# "2.6.0+73b6911". VERSION is build-time only (read here, never deployed), so
# it needs no deployment-manifest entry. If VERSION is missing or empty we fall
# back to the bare hash — identical to the pre-versioning behavior, fail-safe.
ARP_HASH=$(cd "$TEMPLATE_ROOT" && git rev-parse --short HEAD 2>/dev/null || echo "unknown")
ARP_SEMVER=$(tr -d '[:space:]' < "$SRC_ROOT/VERSION" 2>/dev/null || true)
if [ -n "$ARP_SEMVER" ]; then
    ARP_VERSION="${ARP_SEMVER}+${ARP_HASH}"
else
    ARP_VERSION="$ARP_HASH"
fi
# Watermark mode field (LICENSE §2): "manual" marks a research-toolkit
# deployment whose output is human-directed Assisted Output; anything else
# is "autonomous". The pdfsubject provenance phrase softens accordingly so
# the watermark doesn't misattribute assisted work as pipeline-generated.
if [ "$MANUAL" = "1" ]; then
    ARP_MODE="manual"
    ARP_PROVENANCE="Produced with assistance from"
else
    ARP_MODE="autonomous"
    ARP_PROVENANCE="Generated by"
fi
if [ -z "$ARP_UUID" ]; then
    echo "ERROR: failed to generate fingerprint UUID (python3 unavailable or stdlib broken)." >&2
    echo "       Aborting setup; install python3 and retry." >&2
    exit 1
fi
# Skip the paper-skeleton install entirely under --mode report — there is no
# paper being produced, so the fingerprint .sty, main.tex, and IA template
# have nothing to attach to. The ARP_UUID is still recorded in the deployment
# manifest below for traceability.
if [ "$MODE" != "report" ]; then
    sed -e "s|{{ARP_UUID}}|$ARP_UUID|g" \
        -e "s|{{ARP_VERSION}}|$ARP_VERSION|g" \
        -e "s|{{ARP_DATE}}|$ARP_DATE|g" \
        -e "s|{{ARP_MODE}}|$ARP_MODE|g" \
        -e "s|{{ARP_PROVENANCE}}|$ARP_PROVENANCE|g" \
        "$TEMPLATE_ROOT/templates/paper_skeleton/arpipeline.sty.template" \
        > "$P/paper/arpipeline.sty"
    # Don't clobber an existing main.tex (e.g. --seed mode where the user has
    # pre-populated paper/main.tex). The .sty above is always overwritten —
    # it is pipeline infrastructure with a fresh UUID per deployment.
    # Skeleton templates are variant-aware: templates/paper_skeleton/{VARIANT}/
    # overrides the shared root template when present (llm_cognition ships an
    # ML-preprint main.tex — single-column, numeric citations — instead of the
    # economics working-paper format). Root templates are the fallback, so a
    # new variant needs no skeleton files unless its format genuinely differs.
    if [ ! -f "$P/paper/main.tex" ]; then
        MAIN_TEX_TEMPLATE="$TEMPLATE_ROOT/templates/paper_skeleton/main.tex.template"
        [ -f "$TEMPLATE_ROOT/templates/paper_skeleton/$VARIANT/main.tex.template" ] \
            && MAIN_TEX_TEMPLATE="$TEMPLATE_ROOT/templates/paper_skeleton/$VARIANT/main.tex.template"
        cp "$MAIN_TEX_TEMPLATE" "$P/paper/main.tex"
    fi
    # Internet appendix skeleton. paper-writer only populates it when a proof
    # exceeds ~3 pages or the in-paper appendix would otherwise blow past ~30%
    # of main-text length; otherwise it stays a no-op placeholder. Same skip-
    # if-exists guard and variant-override lookup as main.tex above.
    if [ ! -f "$P/paper/internet_appendix.tex" ]; then
        IA_TEX_TEMPLATE="$TEMPLATE_ROOT/templates/paper_skeleton/internet_appendix.tex.template"
        [ -f "$TEMPLATE_ROOT/templates/paper_skeleton/$VARIANT/internet_appendix.tex.template" ] \
            && IA_TEX_TEMPLATE="$TEMPLATE_ROOT/templates/paper_skeleton/$VARIANT/internet_appendix.tex.template"
        cp "$IA_TEX_TEMPLATE" "$P/paper/internet_appendix.tex"
    fi
fi

if [ "$MANUAL" = "1" ]; then
    mkdir -p "$P/output"
elif [ "$MODE" = "report" ]; then
    # Report mode has no stages, no pipeline_state.json, no session/decision/
    # discussion/pattern logs to accumulate. The submission/audits/report/
    # process_log skeleton was created above; nothing else here.
    :
else
    # Stage 2b (theory exploration) is permanently skipped under
    # --mode empirical-first and --mode measurement-first (piloting is part
    # of the design step there); don't create the empty dir in either.
    STAGE2B_DIRS=()
    [ "$MODE" != "empirical-first" ] && [ "$MODE" != "measurement-first" ] && STAGE2B_DIRS=("$P/output/stage2b/figures")
    mkdir -p "$P/output/stage0" "$P/output/stage1" "$P/output/stage2" "${STAGE2B_DIRS[@]}" "$P/output/stage3" "$P/output/stage4" "$P/output/puzzle_triage" "$P/output/post_pipeline"
    mkdir -p "$P/process_log/sessions" "$P/process_log/decisions"
fi

}

setup_project_bootstrap_after_docs() {
if [ "$SEEDED" = "1" ]; then
    mkdir -p "$P/output/seed"
    if [ "$FAITHFUL" = "1" ]; then
    cat > "$P/output/seed/README.md" <<'SEEDREADME'
# Seed folder (faithful mode)

Drop your idea files here before launching the pipeline. The pipeline will read
everything in this folder as the seeded idea.

You can put anything here: markdown notes, PDFs, paper drafts, evaluation
reports, emails, code snippets — whatever describes the idea you want the
pipeline to develop.

This is a **faithful** run: the seed is treated as a contract. Before any other
agent fires, the orchestrator extracts `output/seed/mechanism_contract.md` from
your files — its named mechanism, structural invariants, theorem-statement
constraints, identification strategy, and stated contribution. That contract is
then quoted into every developing agent's launch prompt as a non-negotiable.

What the pipeline will do:
- Implement your seed faithfully — its named mechanism, object of study, and
  identification strategy stay intact. Predicted results (signs, thresholds,
  existence claims, comparative statics) are hypotheses the pipeline tests, not
  frozen conclusions: specify the setup, not the result. A falsified prediction
  gets corrected and documented, not defended.
- Add to / refine / extend the implementation where it can — extra theorems,
  comparative statics, robustness checks.
- Document any genuine impossibility (proof unrepairable, identification
  infeasible, prediction contradicted by data) in `output/seed/limitations.md`
  and ship the paper documenting the impossibility honestly.

What the pipeline will **not** do:
- Substitute a different mechanism, model class, or research design.
- Pivot to a more publishable framing.
- Promote a "buried" result over your stated headline.

If you wanted softer behavior — pipeline preserves the seed but may pivot under
puzzle-triage / refine framing under scorer recommendations — re-run setup with
`--seed` instead of `--faithful`.
SEEDREADME
        echo "  ✓ Seed folder created at output/seed/ (faithful mode) — drop your idea files there before launching"
    else
    cat > "$P/output/seed/README.md" <<'SEEDREADME'
# Seed folder

Drop your idea files here before launching the pipeline. The pipeline will read
everything in this folder as the seeded idea.

You can put anything here: markdown notes, PDFs, paper drafts, evaluation
reports, emails, code snippets — whatever describes the idea you want the
pipeline to develop.

The pipeline reads your files, builds a literature map, assesses maturity, and
enters at the appropriate stage. It will never silently abandon your seeded idea.
If a gate fails, it reports the issue rather than pivoting.
SEEDREADME
        echo "  ✓ Seed folder created at output/seed/ — drop your idea files there before launching"
    fi
fi

# Initial pipeline state (skipped in manual mode — no autonomous pipeline; also
# skipped in report mode — no stages or routing to track, just the audit log)
if [ "$MANUAL" = "1" ]; then
    : # no pipeline state
elif [ "$MODE" = "report" ]; then
    # Seed the audit log so the synthesizer has a stable file to read at the end.
    # The orchestrator appends the launch-time submission hash + per-agent rows
    # per session_report.md's "Update the audit log" instructions.
    cat > "$P/process_log/audit_log.md" <<'AUDITLOG'
# Audit log

The orchestrator computes one submission_hash at launch and records it here,
then appends one row per audit agent on completion. The synthesizer reads this
log before producing the report to confirm coverage.

submission_hash: <not yet computed — set at launch>

| agent | started | completed | output |
|-------|---------|-----------|--------|
AUDITLOG
elif [ "$SEEDED" = "1" ]; then
cat > "$P/process_log/pipeline_state.json" <<JSONEOF
{
  "current_stage": "seed_triage",
  "problem_attempt": 1,
  "theory_attempt": 1,
  "theory_version": 1,
  "regeneration_round": 0,
  "gate0_best_question_score": -1,
  "loops": {
    "gate0_revise":      {"round": 0, "cap": 3},
    "gate0_reject":      {"round": 0, "cap": 5},
    "idea":              {"round": 0, "cap": 5},
    "reject_cosmetic":   {"round": 0, "cap": 2},
    "downgrade_enrich":  {"round": 0, "cap": 2},
    "last_resort_stuck": {"round": 0, "cap": 2},
    "pivot":             {"round": 0, "cap": 2},
    "fix_empirics":      {"round": 0, "cap": 2},
    "referee":           {"round": 0, "cap": 10},
    "bib_verify":        {"round": 0, "cap": 2},
    "polish":            {"round": 0, "cap": 2}
  },
  "pivot_resolved": null,
  "pivot_history": [],
  "triaged_lit_implications": [],
  "target_journal_tier": "__INITIAL_TIER__",
  "initial_journal_tier": "__INITIAL_TIER__",
  "status": "not_started",
  "seeded": true,
  "faithful": $([ "$FAITHFUL" = "1" ] && echo true || echo false),
  "halt_on_core_bypass": $([ "$HALT_ON_CORE_BYPASS" = "1" ] && echo true || echo false),
  "pending_verification": [],
  "scores": {},
  "stage2b_theory_version": null,
  "stage1_candidates": [],
  "history": []
}
JSONEOF
    sed -i.bak "s|__INITIAL_TIER__|$INITIAL_TIER|g" "$P/process_log/pipeline_state.json" && rm "$P/process_log/pipeline_state.json.bak"
else
cat > "$P/process_log/pipeline_state.json" <<'JSONEOF'
{
  "current_stage": "stage_0",
  "problem_attempt": 1,
  "theory_attempt": 1,
  "theory_version": 1,
  "regeneration_round": 0,
  "gate0_best_question_score": -1,
  "loops": {
    "gate0_revise":      {"round": 0, "cap": 3},
    "gate0_reject":      {"round": 0, "cap": 5},
    "idea":              {"round": 0, "cap": 5},
    "reject_cosmetic":   {"round": 0, "cap": 2},
    "downgrade_enrich":  {"round": 0, "cap": 2},
    "last_resort_stuck": {"round": 0, "cap": 2},
    "pivot":             {"round": 0, "cap": 2},
    "fix_empirics":      {"round": 0, "cap": 2},
    "referee":           {"round": 0, "cap": 10},
    "bib_verify":        {"round": 0, "cap": 2},
    "polish":            {"round": 0, "cap": 2}
  },
  "pivot_resolved": null,
  "pivot_history": [],
  "triaged_lit_implications": [],
  "target_journal_tier": "__INITIAL_TIER__",
  "initial_journal_tier": "__INITIAL_TIER__",
  "seeded": false,
  "faithful": false,
  "halt_on_core_bypass": __HALT_ON_CORE_BYPASS__,
  "status": "not_started",
  "pending_verification": [],
  "scores": {},
  "stage2b_theory_version": null,
  "stage1_candidates": [],
  "history": []
}
JSONEOF
    sed -i.bak "s|__INITIAL_TIER__|$INITIAL_TIER|g; s|__HALT_ON_CORE_BYPASS__|$([ "$HALT_ON_CORE_BYPASS" = "1" ] && echo true || echo false)|g" "$P/process_log/pipeline_state.json" && rm "$P/process_log/pipeline_state.json.bak"
fi

# pipeline_state.json: measurement-first adds stage2_design_version — the
# plan-time design gate's version pointer (Gate 4 blocks while it lags
# theory_version), mirroring empirical-first's stage2_mechanism_version. The
# theory_llm extension adds stage3b_theory_version separately below.
if [ "$MODE" = "measurement-first" ] && [ -f "$P/process_log/pipeline_state.json" ]; then
    python3 - "$P/process_log/pipeline_state.json" <<'PYMF'
import json, sys
p = sys.argv[1]
with open(p) as f:
    data = json.load(f)
if "stage2_design_version" not in data:
    new = {}
    for k, v in data.items():
        new[k] = v
        if k == "stage2b_theory_version":
            new["stage2_design_version"] = None
    with open(p, "w") as f:
        json.dump(new, f, indent=2)
        f.write("\n")
PYMF
fi

if [ "$MANUAL" = "0" ] && [ "$MODE" != "report" ]; then
    touch "$P/process_log/history.md"
fi

# Core-bypass degradation ledger (issue #51). Seeded for every autonomous mode
# that has a process_log/ (i.e. non-manual, including report mode). Agents and the
# orchestrator append one row per silent-degradation event per docs/core_bypass.md;
# a non-empty ledger must surface in the run summary. Manual mode has no process_log/,
# so the agent pointer there degrades to "state it in your returned report."
if [ "$MANUAL" = "0" ]; then
    cat > "$P/process_log/degradation_ledger.md" <<'LEDGEREOF'
# Degradation ledger — core-bypass events

Each row records a point where a **core** (a binding external source, a
verification gate, or a designated agent / stage step) was unavailable, skipped,
substituted, or replaced by a weaker fallback. See `docs/core_bypass.md` for the
guard. Default behavior is record-and-surface; under `--halt-on-core-bypass`
(`"halt_on_core_bypass": true` in pipeline_state.json) the run halts after
recording. A non-empty ledger MUST appear in the run summary — a degraded run
never reports clean success. Empty = no core was bypassed.

`action` ∈ {`recorded`, `halted`, `resolved`}. A `binding? = yes` row is
*unresolved* until the verification is re-run as binding and its `action` is set
to `resolved`. An unresolved binding row blocks a plain `status = "complete"` even
in the default deploy. Which way it blocks depends on the outage: a **deferrable**
one (a rate/credit limit with a stated reset horizon, where re-checking is a cheap
lookup) finishes the run and sets `status = "complete_pending_verification"` with
the owed check recorded in `pending_verification`; anything else sets
`status = "halted_core_bypass"`. Either way the run never reports clean success on
a downgraded core — that is the terminal backstop. A running session may set a row
`resolved` only for a binding verification it re-ran itself and that came back
clean; every other resolution is operator-driven. Report mode has no
`pipeline_state.json` / `status` machine, so the blocking rule does not apply
there — rows are recorded and surfaced in the returned report only.

| timestamp | stage | core | condition | why | fallback | binding? | action |
|-----------|-------|------|-----------|-----|----------|----------|--------|
LEDGEREOF
fi

# Faithful mode: seed pivot_log.md with a header + table skeleton so the
# orchestrator has a target to append to. Each routing decision that could
# affect the mechanism contract appends a row per faithful.md's instructions.
if [ "$FAITHFUL" = "1" ]; then
    cat > "$P/process_log/pivot_log.md" <<'PIVOTLOG'
# Pivot log (faithful mode)

Every potentially-mechanism-affecting routing decision is logged here. See
`CLAUDE.md` (the assembled `faithful.md` block) for the routing rules. Each row
records what an evaluator agent reported, how the orchestrator classified it
under the faithful contract, and why.

| timestamp | stage | agent | verdict | classification | rationale |
|-----------|-------|-------|---------|----------------|-----------|
PIVOTLOG
fi

echo "  ✓ Project structure created"

}

setup_project_environment_bootstrap() {
    # Falls back to the committed .env.example so a fresh clone still lands a
    # scaffold. Values are mutable project state: update.sh merges missing keys
    # instead of replacing this file.
    if [ -f "$SCRIPT_DIR/.env" ]; then
        cp "$SCRIPT_DIR/.env" "$P/.env"
        # update.sh's line reader would drop a final unterminated line.
        [ -n "$(tail -c1 "$P/.env")" ] && printf '\n' >> "$P/.env"
        echo "  ✓ .env copied from template repo"
        if [ -f "$SCRIPT_DIR/.env.example" ]; then
            . "$TEMPLATE_ROOT/scripts/merge_env_keys.sh"
            merge_env_missing_keys "$SCRIPT_DIR/.env.example" "$P/.env" 0
            [ "$MERGE_ENV_ADDED" -gt 0 ] \
                && echo "  ✓ $MERGE_ENV_ADDED key(s) added from .env.example — fill in values if you use them"
        fi
    elif [ -f "$SCRIPT_DIR/.env.example" ]; then
        cp "$SCRIPT_DIR/.env.example" "$P/.env"
        echo "  ✓ .env scaffolded from .env.example — fill in your credentials"
    fi
    [ -f "$P/.env" ] && bootstrap_env_merge 10 ".env"
}
